server:
  port: 8084
  
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://doctorService.mssql.somee.com;databaseName=doctorService;TrustServerCertificate=True;?&useSSL=false
    username: sagender_SQLLogin_1
    password: 8badzt5se1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  application:
    name: Especialidad-SERVICE
    
